def Settings( **kwargs ):
  return {
    'flags': [
                # '-x',
                # 'c++',
                '-Wall',
                '-Wextra',
                '-Werror',
                "-std=c++17",

                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source",
                "-I/mnt/c/Users/jonathon/projects/battle_tank_game/BattleTank/Source/BattleTank/Private",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/Engine",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/AI",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/AI/Navigation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Analytics",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Animation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Audio",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Blueprint",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Curves",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/EdGraph",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Internationalization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Net",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Net/Util",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/PacketHandlers",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Performance",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Physics",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Physics/Experimental",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Physics/ImmediatePhysics",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Physics/ImmediatePhysics/ImmediatePhysicsChaos",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Physics/ImmediatePhysics/ImmediatePhysicsPhysX",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Physics/ImmediatePhysics/ImmediatePhysicsShared",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Physics/Tests",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/ProfilingDebugging",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Rendering",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Slate",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Subsystems",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/Tests",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/VisualLogger",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Engine/Public/VT",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/TraceLog/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Algo",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Algo/Impl",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Async",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Clang",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Concepts",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Containers",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Delegates",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Features",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/FramePro",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/GenericPlatform",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/HAL",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/HAL/Allocators",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Hash",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Internationalization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/IO",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Logging",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Math",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Memory",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/MemPro",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Misc",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Modules",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Modules/Boilerplate",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/MSVC",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/ProfilingDebugging",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Serialization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Serialization/Csv",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Serialization/Formatters",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Stats",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Templates",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Traits",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/UObject",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Core/Public/Windows",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/TraceLog",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/TraceLog/Public/Trace",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/TraceLog/Public/Trace/Detail",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/CoreUObject",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject/Public/Blueprint",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject/Public/Internationalization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject/Public/Misc",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject/Public/Serialization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject/Public/Serialization/Formatters",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject/Public/Templates",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/CoreUObject/Public/UObject",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/NetCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Net",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Net/Core/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Net/Core/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Net/Core",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Net/Core/Public/Net",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Net/Core/Public/Net/Core",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Net/Core/Public/Net/Core/Analytics",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Net/Core/Public/Net/Core/Misc",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ApplicationCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ApplicationCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ApplicationCore/Public/GenericPlatform",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ApplicationCore/Public/HAL",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ApplicationCore/Public/Windows",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ApplicationCore/Public/Windows/Accessibility",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/RHI/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/RHI",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Json/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Json",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Json/Public/Dom",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Json/Public/Policies",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Json/Public/Serialization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/SlateCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Animation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Application",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Brushes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Debugging",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/FastUpdate",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Fonts",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Input",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Layout",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Rendering",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Sound",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Styling",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Textures",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Types",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Widgets",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Widgets/Accessibility",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SlateCore/Public/Widgets/Images",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/InputCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/InputCore/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/InputCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/InputCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/InputCore/Public/GenericPlatform",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/InputCore/Public/HAL",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/InputCore/Public/Windows",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/Slate",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Application",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Commands",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Docking",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Layout",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/MetaData",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/MultiBox",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Notifications",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Styling",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Text",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Text/Windows",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Framework/Views",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Accessibility",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Colors",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Docking",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Images",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Input",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/LayerManager",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Layout",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Navigation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Notifications",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Text",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Slate/Public/Widgets/Views",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/ImageWrapper",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ImageWrapper/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ImageWrapper",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Messaging/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Messaging",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MessagingCommon/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MessagingCommon",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/RenderCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/RenderCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/RenderCore/Public/ProfilingDebugging",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Sockets/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Sockets",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AssetRegistry",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AssetRegistry/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AssetRegistry",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/EngineMessages",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/EngineMessages/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/EngineMessages",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/EngineSettings",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/EngineSettings/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/EngineSettings/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/EngineSettings",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SynthBenchmark/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SynthBenchmark",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/Renderer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Renderer/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Renderer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Renderer/Public/VT",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/GameplayTags",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/GameplayTags/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/GameplayTags/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/GameplayTags",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/PacketHandler",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PacketHandlers",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PacketHandlers/PacketHandler/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PacketHandlers/PacketHandler/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PacketHandlers/PacketHandler",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PacketHandlers/ReliabilityHandlerComponent/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PacketHandlers/ReliabilityHandlerComponent",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AudioPlatformConfiguration",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioPlatformConfiguration/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioPlatformConfiguration",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/MeshDescription",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MeshDescription/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MeshDescription",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/StaticMeshDescription",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/StaticMeshDescription/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/StaticMeshDescription",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PakFile/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PakFile",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/RSA/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/RSA",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NetworkReplayStreaming",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NetworkReplayStreaming/NetworkReplayStreaming/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NetworkReplayStreaming/NetworkReplayStreaming",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/PhysicsCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PhysicsCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PhysicsCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/Chaos/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/Chaos",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/Chaos/Public/Chaos",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/Chaos/Public/Chaos/Framework",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/ChaosCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/ChaosCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/ChaosCore/Public/Chaos",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/Voronoi/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/Voronoi",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/Voronoi/Public/Voronoi",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/FieldSystemCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/FieldSystem/Source",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/FieldSystem/Source/FieldSystemCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/FieldSystem/Source/FieldSystemCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/FieldSystem/Source/FieldSystemCore/Public/Field",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SignalProcessing/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SignalProcessing",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SignalProcessing/Public/DSP",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SignalProcessing/Public/DSP/Encoders",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/UnrealEd",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Programs/UnrealLightmass/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/Android/AndroidDeviceDetection/Public/Interfaces",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/AutoReimport",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Bookmarks",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Commandlets",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Dialogs",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/DragAndDrop",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Features",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Kismet2",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Layers",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Settings",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Subsystems",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Tests",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Toolkits",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEd/Public/Tools",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/BspMode/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/BspMode",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/DirectoryWatcher/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/DirectoryWatcher",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/Documentation/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/Documentation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Projects/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Projects",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Projects/Public/Interfaces",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SandboxFile/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/SandboxFile",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/EditorStyle",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/EditorStyle/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/EditorStyle",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/EditorStyle/Public/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/EditorStyle/Public/Interfaces",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/SourceControl",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/SourceControl/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/SourceControl",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/SourceControl/Public/Tests",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/UnrealEdMessages",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEdMessages/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEdMessages/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/UnrealEdMessages",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/GameplayDebugger",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/GameplayDebugger/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/GameplayDebugger",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/BlueprintGraph",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/BlueprintGraph/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/BlueprintGraph/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/BlueprintGraph",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/EditorSubsystem",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/EditorSubsystem/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/EditorSubsystem",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Online",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Online/HTTP/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Online/HTTP",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Online/HTTP/Public/GenericPlatform",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Online/HTTP/Public/Interfaces",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Online/HTTP/Public/Windows",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UnrealAudio/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UnrealAudio",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/FunctionalTesting",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/FunctionalTesting/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/FunctionalTesting/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/FunctionalTesting",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AutomationController",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/AutomationController/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/AutomationController",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/Localization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/Localization/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/Localization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/Localization/Public/Serialization",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AudioEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/AudioEditor/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/AudioEditor/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/AudioEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/AudioEditor/Public/AssetTypeActions",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AudioMixer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixer/Private",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixer/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixer/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixer/Public/Components",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixer/Public/DSP",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixer/Public/SoundFileIO",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/TargetPlatform/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/TargetPlatform",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/TargetPlatform/Public/Common",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/TargetPlatform/Public/Interfaces",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/libSampleRate/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/libSampleRate",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/LevelEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/LevelEditor/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/LevelEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/Settings/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/Settings",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/IntroTutorials",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/IntroTutorials/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/IntroTutorials",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/HeadMountedDisplay",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/HeadMountedDisplay/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/HeadMountedDisplay",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/VREditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/VREditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/VREditor/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/CommonMenuExtensions/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/CommonMenuExtensions",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/Landscape",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Landscape/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Landscape/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Landscape",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/PropertyEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/PropertyEditor/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/PropertyEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/ActorPickerMode/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/ActorPickerMode",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/SceneDepthPickerMode/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/SceneDepthPickerMode",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/DetailCustomizations",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/DetailCustomizations/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/DetailCustomizations",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/DetailCustomizations/Public/Customizations",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/ClassViewer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/ClassViewer/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/ClassViewer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/GraphEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/GraphEditor/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/GraphEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/GraphEditor/Public/DragAndDrop",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/GraphEditor/Public/KismetNodes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/GraphEditor/Public/KismetPins",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/StructViewer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/StructViewer/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/StructViewer",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/ContentBrowser",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/ContentBrowser/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/ContentBrowser",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NetworkFileSystem/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NetworkFileSystem",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/UMG",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UMG/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UMG",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UMG/Public/Animation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UMG/Public/Binding",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UMG/Public/Blueprint",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UMG/Public/Components",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UMG/Public/Editor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/UMG/Public/Slate",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/MovieScene",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene/Public/Channels",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene/Public/Compilation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene/Public/Evaluation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene/Public/Evaluation/Blending",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene/Public/Generators",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene/Public/Sections",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieScene/Public/Tracks",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/TimeManagement",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/TimeManagement/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/TimeManagement",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/TimeManagement/Public/Widgets",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/MovieSceneTracks",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieSceneTracks/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieSceneTracks",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieSceneTracks/Public/Channels",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieSceneTracks/Public/Evaluation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieSceneTracks/Public/Sections",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MovieSceneTracks/Public/Tracks",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AnimationCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AnimationCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AnimationCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/PropertyPath",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PropertyPath/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PropertyPath",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/NavigationSystem",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NavigationSystem/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NavigationSystem",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NavigationSystem/Public/NavAreas",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NavigationSystem/Public/NavFilters",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NavigationSystem/Public/NavGraph",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/NavigationSystem/Public/NavMesh",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/MeshDescriptionOperations",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshDescriptionOperations/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshDescriptionOperations",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshBuilder/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshBuilder",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/MaterialShaderQualitySettings",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MaterialShaderQualitySettings/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/MaterialShaderQualitySettings",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/InteractiveToolsFramework",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/InteractiveToolsFramework/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/InteractiveToolsFramework",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/InteractiveToolsFramework/Public/BaseBehaviors",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/InteractiveToolsFramework/Public/BaseGizmos",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/InteractiveToolsFramework/Public/BaseTools",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/InteractiveToolsFramework/Public/Changes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/ToolMenusEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/ToolMenusEditor/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/ToolMenusEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Windows",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Windows/XAudio2/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Windows/XAudio2",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Windows/AudioMixerXAudio2",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/AssetTagsEditor/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/AssetTagsEditor",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/CollectionManager/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/CollectionManager",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AddContentDialog",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/AddContentDialog/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/AddContentDialog",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/IntelEmbree/Embree2140/Win64/include",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshUtilities/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshUtilities",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshMergeUtilities/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshMergeUtilities",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/HierarchicalLODUtilities/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/HierarchicalLODUtilities",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshReductionInterface/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/MeshReductionInterface",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AssetTools",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/AssetTools/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/AssetTools",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Developer/AssetTools/Public/AssetTypeActions",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/KismetCompiler/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/KismetCompiler",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/GameplayTasks",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/GameplayTasks/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/GameplayTasks/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/GameplayTasks",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/AIModule",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AIModule/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AIModule/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AIModule",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/Kismet",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/Kismet/Classes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/Kismet/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/Kismet",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/Kismet/Public/Nodes",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Editor/Kismet/Public/WorkflowOrientedApp",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PhysicsSQ/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/PhysicsSQ",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/ChaosSolvers",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/ChaosSolvers/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/ChaosSolvers",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/ChaosSolvers/Public/Framework",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/ChaosSolvers/Public/PhysicsProxy",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/GeometryCollectionCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/GeometryCollectionCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/GeometryCollectionCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/GeometryCollectionCore/Public/GeometryCollection",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/GeometryCollectionSimulationCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/GeometryCollectionSimulationCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/GeometryCollectionSimulationCore",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/Experimental/GeometryCollectionSimulationCore/Public/GeometryCollection",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Intermediate/Build/Win64/UE4Editor/Inc/ClothingSystemRuntimeInterface",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ClothingSystemRuntimeInterface/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/ClothingSystemRuntimeInterface",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixerCore/Public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/Runtime/AudioMixerCore",
                "-I/mnt/c/Users/jonathon/projects/battle_tank_game/BattleTank/Intermediate/Build/Win64/UE4Editor/Inc/BattleTank",
                "-I/mnt/c/Users/jonathon/projects/battle_tank_game/BattleTank/Source",
                "-I/mnt/c/Users/jonathon/projects/battle_tank_game/BattleTank/Source/BattleTank/Public",
                "-I/mnt/c/Users/jonathon/projects/battle_tank_game/BattleTank/Source/BattleTank",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PxShared/include",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PxShared/include/cudamanager",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PxShared/include/filebuf",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PxShared/include/foundation",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PxShared/include/pvd",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PxShared/include/task",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include/cooking",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include/common",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include/extensions",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Include/geometry",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include/clothing",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include/nvparameterized",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include/legacy",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/include/PhysX3",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/common/include",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/common/include/autogen",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/framework/include",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/framework/include/autogen",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/shared/general/RenderDebug/public",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/shared/general/PairFilter/include",
                "-I/mnt/c/Program Files/Epic Games/UE_4.24/Engine/Source/ThirdParty/PhysX3/APEX_1.4/shared/internal/include",
                "-I/mnt/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/INCLUDE",
                "-I/mnt/c/Program Files (x86)/Windows Kits/NETFXSDK/4.6.1/include/um",
                "-I/mnt/c/Program Files (x86)/Windows Kits/10/include/10.0.17763.0/ucrt",
                "-I/mnt/c/Program Files (x86)/Windows Kits/10/include/10.0.17763.0/shared",
                "-I/mnt/c/Program Files (x86)/Windows Kits/10/include/10.0.17763.0/um",
                "-I/mnt/c/Program Files (x86)/Windows Kits/10/include/10.0.17763.0/winrt",

                "-DIS_PROGRAM=0",
                "-DUE_EDITOR=1",
                "-DENABLE_PGO_PROFILE=0",
                "-DUSE_VORBIS_FOR_STREAMING=1",
                "-DUSE_XMA2_FOR_STREAMING=1",
                "-DWITH_DEV_AUTOMATION_TESTS=1",
                "-DWITH_PERF_AUTOMATION_TESTS=1",
                "-DUNICODE",
                "-D_UNICODE",
                "-D__UNREAL__",
                "-DIS_MONOLITHIC=0",
                "-DWITH_ENGINE=1",
                "-DWITH_UNREAL_DEVELOPER_TOOLS=1",
                "-DWITH_APPLICATION_CORE=1",
                "-DWITH_COREUOBJECT=1",
                "-DUSE_STATS_WITHOUT_ENGINE=0",
                "-DWITH_PLUGIN_SUPPORT=0",
                "-DWITH_ACCESSIBILITY=1",
                "-DWITH_PERFCOUNTERS=1",
                "-DUSE_LOGGING_IN_SHIPPING=0",
                "-DWITH_LOGGING_TO_MEMORY=0",
                "-DUSE_CACHE_FREED_OS_ALLOCS=1",
                "-DUSE_CHECKS_IN_SHIPPING=0",
                "-DWITH_EDITOR=1",
                "-DWITH_SERVER_CODE=1",
                "-DWITH_CEF3=1",
                "-DWITH_LIVE_CODING=1",
                "-DWITH_XGE_CONTROLLER=1",
                "-DUBT_MODULE_MANIFEST=\"UE4Editor.modules\"",
                "-DUBT_MODULE_MANIFEST_DEBUGGAME=\"UE4Editor-Win64-DebugGame.modules\"",
                "-DUBT_COMPILED_PLATFORM=Win64",
                "-DUBT_COMPILED_TARGET=Editor",
                "-DUE_APP_NAME=\"UE4Editor\"",
                "-DNDIS_MINIPORT_MAJOR_VERSION=0",
                "-DWIN32=1",
                "-D_WIN32_WINNT=0x0601",
                "-DWINVER=0x0601",
                "-DPLATFORM_WINDOWS=1",
                "-DOVERRIDE_PLATFORM_HEADER_NAME=Windows",
                "-DNDEBUG=1",
                "-DUE_BUILD_DEVELOPMENT=1",
                "-DUE_IS_ENGINE_MODULE=0",
                "-DUE_PROJECT_NAME=BattleTank",
                "-DIMPLEMENT_ENCRYPTION_KEY_REGISTRATION()=",
                "-DIMPLEMENT_SIGNING_KEY_REGISTRATION()=",
                "-DDEPRECATED_FORGAME=DEPRECATED",
                "-DUE_DEPRECATED_FORGAME=UE_DEPRECATED",
                "-DINCLUDE_CHAOS=0",
                "-DWITH_PHYSX=1",
                "-DWITH_CHAOS=0",
                "-DWITH_CHAOS_CLOTHING=0",
                "-DWITH_CHAOS_NEEDS_TO_BE_FIXED=0",
                "-DPHYSICS_INTERFACE_PHYSX=1",
                "-DWITH_APEX=1",
                "-DWITH_APEX_CLOTHING=1",
                "-DWITH_CLOTH_COLLISION_DETECTION=1",
                "-DWITH_PHYSX_COOKING=1",
                "-DWITH_NVCLOTH=1",
                "-DWITH_CUSTOM_SQ_STRUCTURE=0",
                "-DWITH_IMMEDIATE_PHYSX=0",
                "-DGPUPARTICLE_LOCAL_VF_ONLY=0",
                "-DENGINE_VTABLE=DLLIMPORT_VTABLE",
                "-DENGINE_API=",
                "-DUE_ENABLE_ICU=1",
                "-DWITH_VS_PERF_PROFILER=0",
                "-DWITH_DIRECTXMATH=0",
                "-DWITH_MALLOC_STOMP=1",
                "-DCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DCORE_API=",
                "-DTRACELOG_VTABLE=DLLIMPORT_VTABLE",
                "-DTRACELOG_API=",
                "-DCOREUOBJECT_VTABLE=DLLIMPORT_VTABLE",
                "-DCOREUOBJECT_API=",
                "-DNETCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DNETCORE_API=",
                "-DAPPLICATIONCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DAPPLICATIONCORE_API=",
                "-DRHI_VTABLE=DLLIMPORT_VTABLE",
                "-DRHI_API=",
                "-DJSON_VTABLE=DLLIMPORT_VTABLE",
                "-DJSON_API=",
                "-DWITH_FREETYPE=1",
                "-DSLATECORE_VTABLE=DLLIMPORT_VTABLE",
                "-DSLATECORE_API=",
                "-DINPUTCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DINPUTCORE_API=",
                "-DSLATE_VTABLE=DLLIMPORT_VTABLE",
                "-DSLATE_API=",
                "-DWITH_UNREALPNG=1",
                "-DWITH_UNREALJPEG=1",
                "-DWITH_UNREALEXR=1",
                "-DIMAGEWRAPPER_VTABLE=DLLIMPORT_VTABLE",
                "-DIMAGEWRAPPER_API=",
                "-DMESSAGING_VTABLE=DLLIMPORT_VTABLE",
                "-DMESSAGING_API=",
                "-DMESSAGINGCOMMON_VTABLE=DLLIMPORT_VTABLE",
                "-DMESSAGINGCOMMON_API=",
                "-DRENDERCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DRENDERCORE_API=",
                "-DSOCKETS_PACKAGE=1",
                "-DSOCKETS_VTABLE=DLLIMPORT_VTABLE",
                "-DSOCKETS_API=",
                "-DASSETREGISTRY_VTABLE=DLLIMPORT_VTABLE",
                "-DASSETREGISTRY_API=",
                "-DENGINEMESSAGES_VTABLE=DLLIMPORT_VTABLE",
                "-DENGINEMESSAGES_API=",
                "-DENGINESETTINGS_VTABLE=DLLIMPORT_VTABLE",
                "-DENGINESETTINGS_API=",
                "-DSYNTHBENCHMARK_VTABLE=DLLIMPORT_VTABLE",
                "-DSYNTHBENCHMARK_API=",
                "-DRENDERER_VTABLE=DLLIMPORT_VTABLE",
                "-DRENDERER_API=",
                "-DGAMEPLAYTAGS_VTABLE=DLLIMPORT_VTABLE",
                "-DGAMEPLAYTAGS_API=",
                "-DPACKETHANDLER_VTABLE=DLLIMPORT_VTABLE",
                "-DPACKETHANDLER_API=",
                "-DRELIABILITYHANDLERCOMPONENT_VTABLE=DLLIMPORT_VTABLE",
                "-DRELIABILITYHANDLERCOMPONENT_API=",
                "-DAUDIOPLATFORMCONFIGURATION_VTABLE=DLLIMPORT_VTABLE",
                "-DAUDIOPLATFORMCONFIGURATION_API=",
                "-DMESHDESCRIPTION_VTABLE=DLLIMPORT_VTABLE",
                "-DMESHDESCRIPTION_API=",
                "-DSTATICMESHDESCRIPTION_VTABLE=DLLIMPORT_VTABLE",
                "-DSTATICMESHDESCRIPTION_API=",
                "-DPAKFILE_VTABLE=DLLIMPORT_VTABLE",
                "-DPAKFILE_API=",
                "-DRSA_VTABLE=DLLIMPORT_VTABLE",
                "-DRSA_API=",
                "-DNETWORKREPLAYSTREAMING_VTABLE=DLLIMPORT_VTABLE",
                "-DNETWORKREPLAYSTREAMING_API=",
                "-DPHYSICSCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DPHYSICSCORE_API=",
                "-DCOMPILE_WITHOUT_UNREAL_SUPPORT=0",
                "-DCHAOS_MEMORY_TRACKING=0",
                "-DCHAOS_VTABLE=DLLIMPORT_VTABLE",
                "-DCHAOS_API=",
                "-DCHAOS_CHECKED=0",
                "-DCHAOSCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DCHAOSCORE_API=",
                "-DINTEL_ISPC=1",
                "-DVORONOI_VTABLE=DLLIMPORT_VTABLE",
                "-DVORONOI_API=",
                "-DFIELDSYSTEMCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DFIELDSYSTEMCORE_API=",
                "-DWITH_PHYSX_RELEASE=0",
                "-DUE_PHYSX_SUFFIX=PROFILE",
                "-DUE_APEX_SUFFIX=PROFILE",
                "-DAPEX_UE4=1",
                "-DAPEX_STATICALLY_LINKED=0",
                "-DWITH_APEX_LEGACY=1",
                "-DSIGNALPROCESSING_VTABLE=DLLIMPORT_VTABLE",
                "-DSIGNALPROCESSING_API=",
                "-DWITH_RECAST=1",
                "-DUNREALED_VTABLE=DLLIMPORT_VTABLE",
                "-DUNREALED_API=",
                "-DBSPMODE_VTABLE=DLLIMPORT_VTABLE",
                "-DBSPMODE_API=",
                "-DDIRECTORYWATCHER_VTABLE=DLLIMPORT_VTABLE",
                "-DDIRECTORYWATCHER_API=",
                "-DDOCUMENTATION_VTABLE=DLLIMPORT_VTABLE",
                "-DDOCUMENTATION_API=",
                "-DLOAD_PLUGINS_FOR_TARGET_PLATFORMS=1",
                "-DPROJECTS_VTABLE=DLLIMPORT_VTABLE",
                "-DPROJECTS_API=",
                "-DSANDBOXFILE_VTABLE=DLLIMPORT_VTABLE",
                "-DSANDBOXFILE_API=",
                "-DEDITORSTYLE_VTABLE=DLLIMPORT_VTABLE",
                "-DEDITORSTYLE_API=",
                "-DSOURCE_CONTROL_WITH_SLATE=1",
                "-DSOURCECONTROL_VTABLE=DLLIMPORT_VTABLE",
                "-DSOURCECONTROL_API=",
                "-DUNREALEDMESSAGES_VTABLE=DLLIMPORT_VTABLE",
                "-DUNREALEDMESSAGES_API=",
                "-DGAMEPLAYDEBUGGER_VTABLE=DLLIMPORT_VTABLE",
                "-DGAMEPLAYDEBUGGER_API=",
                "-DBLUEPRINTGRAPH_VTABLE=DLLIMPORT_VTABLE",
                "-DBLUEPRINTGRAPH_API=",
                "-DEDITORSUBSYSTEM_VTABLE=DLLIMPORT_VTABLE",
                "-DEDITORSUBSYSTEM_API=",
                "-DHTTP_PACKAGE=1",
                "-DCURL_ENABLE_DEBUG_CALLBACK=1",
                "-DCURL_ENABLE_NO_TIMEOUTS_OPTION=1",
                "-DHTTP_VTABLE=DLLIMPORT_VTABLE",
                "-DHTTP_API=",
                "-DUNREALAUDIO_VTABLE=DLLIMPORT_VTABLE",
                "-DUNREALAUDIO_API=",
                "-DFUNCTIONALTESTING_VTABLE=DLLIMPORT_VTABLE",
                "-DFUNCTIONALTESTING_API=",
                "-DAUTOMATIONCONTROLLER_VTABLE=DLLIMPORT_VTABLE",
                "-DAUTOMATIONCONTROLLER_API=",
                "-DLOCALIZATION_VTABLE=DLLIMPORT_VTABLE",
                "-DLOCALIZATION_API=",
                "-DWITH_SNDFILE_IO=1",
                "-DAUDIOEDITOR_VTABLE=DLLIMPORT_VTABLE",
                "-DAUDIOEDITOR_API=",
                "-DAUDIOMIXER_VTABLE=DLLIMPORT_VTABLE",
                "-DAUDIOMIXER_API=",
                "-DTARGETPLATFORM_VTABLE=DLLIMPORT_VTABLE",
                "-DTARGETPLATFORM_API=",
                "-DUELIBSAMPLERATE_VTABLE=DLLIMPORT_VTABLE",
                "-DUELIBSAMPLERATE_API=",
                "-DLEVELEDITOR_VTABLE=DLLIMPORT_VTABLE",
                "-DLEVELEDITOR_API=",
                "-DSETTINGS_VTABLE=DLLIMPORT_VTABLE",
                "-DSETTINGS_API=",
                "-DINTROTUTORIALS_VTABLE=DLLIMPORT_VTABLE",
                "-DINTROTUTORIALS_API=",
                "-DHEADMOUNTEDDISPLAY_VTABLE=DLLIMPORT_VTABLE",
                "-DHEADMOUNTEDDISPLAY_API=",
                "-DVREDITOR_VTABLE=DLLIMPORT_VTABLE",
                "-DVREDITOR_API=",
                "-DCOMMONMENUEXTENSIONS_VTABLE=DLLIMPORT_VTABLE",
                "-DCOMMONMENUEXTENSIONS_API=",
                "-DLANDSCAPE_VTABLE=DLLIMPORT_VTABLE",
                "-DLANDSCAPE_API=",
                "-DPROPERTYEDITOR_VTABLE=DLLIMPORT_VTABLE",
                "-DPROPERTYEDITOR_API=",
                "-DACTORPICKERMODE_VTABLE=DLLIMPORT_VTABLE",
                "-DACTORPICKERMODE_API=",
                "-DSCENEDEPTHPICKERMODE_VTABLE=DLLIMPORT_VTABLE",
                "-DSCENEDEPTHPICKERMODE_API=",
                "-DDETAILCUSTOMIZATIONS_VTABLE=DLLIMPORT_VTABLE",
                "-DDETAILCUSTOMIZATIONS_API=",
                "-DCLASSVIEWER_VTABLE=DLLIMPORT_VTABLE",
                "-DCLASSVIEWER_API=",
                "-DGRAPHEDITOR_VTABLE=DLLIMPORT_VTABLE",
                "-DGRAPHEDITOR_API=",
                "-DSTRUCTVIEWER_VTABLE=DLLIMPORT_VTABLE",
                "-DSTRUCTVIEWER_API=",
                "-DCONTENTBROWSER_VTABLE=DLLIMPORT_VTABLE",
                "-DCONTENTBROWSER_API=",
                "-DENABLE_HTTP_FOR_NFS=1",
                "-DNETWORKFILESYSTEM_VTABLE=DLLIMPORT_VTABLE",
                "-DNETWORKFILESYSTEM_API=",
                "-DUMG_VTABLE=DLLIMPORT_VTABLE",
                "-DUMG_API=",
                "-DMOVIESCENE_VTABLE=DLLIMPORT_VTABLE",
                "-DMOVIESCENE_API=",
                "-DTIMEMANAGEMENT_VTABLE=DLLIMPORT_VTABLE",
                "-DTIMEMANAGEMENT_API=",
                "-DMOVIESCENETRACKS_VTABLE=DLLIMPORT_VTABLE",
                "-DMOVIESCENETRACKS_API=",
                "-DANIMATIONCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DANIMATIONCORE_API=",
                "-DPROPERTYPATH_VTABLE=DLLIMPORT_VTABLE",
                "-DPROPERTYPATH_API=",
                "-DNAVIGATIONSYSTEM_VTABLE=DLLIMPORT_VTABLE",
                "-DNAVIGATIONSYSTEM_API=",
                "-DMESHDESCRIPTIONOPERATIONS_VTABLE=DLLIMPORT_VTABLE",
                "-DMESHDESCRIPTIONOPERATIONS_API=",
                "-DMESHBUILDER_VTABLE=DLLIMPORT_VTABLE",
                "-DMESHBUILDER_API=",
                "-DMATERIALSHADERQUALITYSETTINGS_VTABLE=DLLIMPORT_VTABLE",
                "-DMATERIALSHADERQUALITYSETTINGS_API=",
                "-DINTERACTIVETOOLSFRAMEWORK_VTABLE=DLLIMPORT_VTABLE",
                "-DINTERACTIVETOOLSFRAMEWORK_API=",
                "-DTOOLMENUSEDITOR_VTABLE=DLLIMPORT_VTABLE",
                "-DTOOLMENUSEDITOR_API=",
                "-DWITH_OGGVORBIS=1",
                "-DXAUDIO2_VTABLE=DLLIMPORT_VTABLE",
                "-DXAUDIO2_API=",
                "-DAUDIOMIXERXAUDIO2_VTABLE=DLLIMPORT_VTABLE",
                "-DAUDIOMIXERXAUDIO2_API=",
                "-DASSETTAGSEDITOR_VTABLE=DLLIMPORT_VTABLE",
                "-DASSETTAGSEDITOR_API=",
                "-DCOLLECTIONMANAGER_VTABLE=DLLIMPORT_VTABLE",
                "-DCOLLECTIONMANAGER_API=",
                "-DADDCONTENTDIALOG_VTABLE=DLLIMPORT_VTABLE",
                "-DADDCONTENTDIALOG_API=",
                "-DUSE_EMBREE=1",
                "-DMESHUTILITIES_VTABLE=DLLIMPORT_VTABLE",
                "-DMESHUTILITIES_API=",
                "-DMESHMERGEUTILITIES_VTABLE=DLLIMPORT_VTABLE",
                "-DMESHMERGEUTILITIES_API=",
                "-DHIERARCHICALLODUTILITIES_VTABLE=DLLIMPORT_VTABLE",
                "-DHIERARCHICALLODUTILITIES_API=",
                "-DMESHREDUCTIONINTERFACE_VTABLE=DLLIMPORT_VTABLE",
                "-DMESHREDUCTIONINTERFACE_API=",
                "-DASSETTOOLS_VTABLE=DLLIMPORT_VTABLE",
                "-DASSETTOOLS_API=",
                "-DKISMETCOMPILER_VTABLE=DLLIMPORT_VTABLE",
                "-DKISMETCOMPILER_API=",
                "-DGAMEPLAYTASKS_VTABLE=DLLIMPORT_VTABLE",
                "-DGAMEPLAYTASKS_API=",
                "-DWITH_GAMEPLAY_DEBUGGER=1",
                "-DAIMODULE_VTABLE=DLLIMPORT_VTABLE",
                "-DAIMODULE_API=",
                "-DKISMET_VTABLE=DLLIMPORT_VTABLE",
                "-DKISMET_API=",
                "-DPHYSICSSQ_VTABLE=DLLIMPORT_VTABLE",
                "-DPHYSICSSQ_API=",
                "-DCHAOSSOLVERS_VTABLE=DLLIMPORT_VTABLE",
                "-DCHAOSSOLVERS_API=",
                "-DGEOMETRYCOLLECTIONCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DGEOMETRYCOLLECTIONCORE_API=",
                "-DGEOMETRYCOLLECTIONSIMULATIONCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DGEOMETRYCOLLECTIONSIMULATIONCORE_API=",
                "-DCLOTHINGSYSTEMRUNTIMEINTERFACE_VTABLE=DLLIMPORT_VTABLE",
                "-DCLOTHINGSYSTEMRUNTIMEINTERFACE_API=",
                "-DAUDIOMIXERCORE_VTABLE=DLLIMPORT_VTABLE",
                "-DAUDIOMIXERCORE_API=",
                "-DBATTLETANK_VTABLE=DLLEXPORT_VTABLE",
                "-DBATTLETANK_API="

        ],
  }
